#!/bin/bash
# Interactive setup wizard for Obsidian Vault Manager
# This script configures the plugin for your specific vault

set -e

echo "🚀 Obsidian Vault Manager - Setup Wizard"
echo "=========================================="
echo ""

# Detect current directory
VAULT_PATH="$PWD"

# Check if we're in an Obsidian vault
if [[ ! -d "$VAULT_PATH/.obsidian" ]]; then
    echo "⚠️  Warning: .obsidian folder not found in current directory"
    echo "This script should be run from your Obsidian vault directory."
    echo ""
    echo "Current directory: $VAULT_PATH"
    echo ""
    read -p "Is this your vault directory? (y/n): " CONFIRM

    if [[ "$CONFIRM" != "y" ]]; then
        echo ""
        echo "❌ Setup cancelled."
        echo ""
        echo "Please:"
        echo "1. cd /path/to/your/ObsidianVault"
        echo "2. Run this script again"
        exit 1
    fi
fi

echo "✅ Vault detected: $VAULT_PATH"
echo ""

# Check for required dependencies
echo "🔍 Checking dependencies..."
echo ""

MISSING_DEPS=()

# Check for uvx/uv
if ! command -v uvx &> /dev/null && ! command -v uv &> /dev/null; then
    MISSING_DEPS+=("uv (for YouTube transcripts)")
fi

# Check for jq
if ! command -v jq &> /dev/null; then
    MISSING_DEPS+=("jq (for JSON processing)")
fi

# Check for python3
if ! command -v python3 &> /dev/null; then
    MISSING_DEPS+=("python3 (for image path conversion)")
fi

# Check for git
if ! command -v git &> /dev/null; then
    MISSING_DEPS+=("git (for publishing)")
fi

if [[ ${#MISSING_DEPS[@]} -gt 0 ]]; then
    echo "⚠️  Missing dependencies:"
    for dep in "${MISSING_DEPS[@]}"; do
        echo "  - $dep"
    done
    echo ""
    echo "Install them with: brew install uv jq git"
    echo ""
    read -p "Continue anyway? (y/n): " CONTINUE
    if [[ "$CONTINUE" != "y" ]]; then
        exit 1
    fi
else
    echo "✅ All dependencies found"
fi

echo ""

# Ask about GitHub Pages publishing
echo "📄 GitHub Pages Publishing Setup"
echo "--------------------------------"
read -p "Do you want to enable GitHub Pages publishing? (y/n): " ENABLE_PAGES

if [[ "$ENABLE_PAGES" == "y" ]]; then
    echo ""
    read -p "Enter GitHub Pages repo path (e.g., ~/Dev/my-site): " PAGES_PATH

    # Expand tilde
    PAGES_PATH="${PAGES_PATH/#\~/$HOME}"

    # Check if directory exists
    if [[ ! -d "$PAGES_PATH" ]]; then
        echo "⚠️  Directory not found: $PAGES_PATH"
        read -p "Create it? (y/n): " CREATE_DIR
        if [[ "$CREATE_DIR" == "y" ]]; then
            mkdir -p "$PAGES_PATH"
            mkdir -p "$PAGES_PATH/documents"
            mkdir -p "$PAGES_PATH/images"
            echo "✅ Created directory structure"
        fi
    fi

    read -p "Enter GitHub Pages URL (e.g., https://you.github.io/site): " PAGES_URL

    # Extract repo name from path
    REPO_NAME=$(basename "$PAGES_PATH")
else
    PAGES_PATH="$HOME/Dev/github-pages"
    PAGES_URL="https://user.github.io/repo"
    REPO_NAME="repo"
fi

echo ""
echo "📋 Configuration Summary"
echo "------------------------"
echo "Vault Path:       $VAULT_PATH"
echo "GitHub Pages:     ${ENABLE_PAGES:-n}"
if [[ "$ENABLE_PAGES" == "y" ]]; then
    echo "Pages Repo:       $PAGES_PATH"
    echo "Pages URL:        $PAGES_URL"
    echo "Repo Name:        $REPO_NAME"
fi
echo ""
read -p "Continue with this configuration? (y/n): " CONFIRM

if [[ "$CONFIRM" != "y" ]]; then
    echo "❌ Setup cancelled"
    exit 1
fi

echo ""
echo "⚙️  Creating configuration files..."

# Create .claude directory if needed
mkdir -p "$VAULT_PATH/.claude"

# Create settings.local.json
cat > "$VAULT_PATH/.claude/settings.local.json" << EOF
{
  "env": {
    "OBSIDIAN_VAULT_PATH": "$VAULT_PATH",
    "GITHUB_PAGES_PATH": "$PAGES_PATH",
    "GITHUB_PAGES_URL": "$PAGES_URL",
    "GITHUB_PAGES_REPO_NAME": "$REPO_NAME"
  },
  "permissions": {
    "allow": [
      "Bash(uvx youtube_transcript_api:*)",
      "Bash(git:*)",
      "Bash(find:*)",
      "Bash(curl:*)",
      "Bash(jq:*)",
      "Bash(python3:*)",
      "Bash(~/.claude/plugins/marketplaces/obsidian-vault-manager-plugin/obsidian-vault-manager/scripts/core/*)",
      "Read(//Users/**/obsidian-vault-manager-plugin/**)",
      "mcp__obsidian-mcp-tools__*",
      "mcp__fetch__fetch",
      "mcp__gitingest__gitingest-analyze",
      "SlashCommand(/capture:*)",
      "SlashCommand(/publish:*)",
      "SlashCommand(/setup:*)"
    ]
  },
  "enabledMcpjsonServers": [
    "obsidian-mcp-tools",
    "fetch",
    "gitingest"
  ]
}
EOF

# Create config.sh for bash scripts
cat > "$VAULT_PATH/.claude/config.sh" << EOF
#!/bin/bash
# Obsidian Vault Manager Configuration
# Auto-generated by setup wizard on $(date)

export OBSIDIAN_VAULT_PATH="$VAULT_PATH"
export GITHUB_PAGES_PATH="$PAGES_PATH"
export GITHUB_PAGES_URL="$PAGES_URL"
export GITHUB_PAGES_REPO_NAME="$REPO_NAME"
EOF

chmod +x "$VAULT_PATH/.claude/config.sh"

echo "✅ Configuration files created"
echo ""

# Create .gitignore for vault/.claude if it doesn't exist
if [[ ! -f "$VAULT_PATH/.claude/.gitignore" ]]; then
    cat > "$VAULT_PATH/.claude/.gitignore" << EOF
# Obsidian Vault Manager - Local Configuration
# DO NOT commit these files - they contain personal paths

settings.local.json
config.sh
*.local.*
EOF
    echo "✅ Created .claude/.gitignore"
fi

echo ""
echo "✨ Setup Complete!"
echo "=================="
echo ""
echo "Configuration saved to:"
echo "  📄 $VAULT_PATH/.claude/settings.local.json"
echo "  📄 $VAULT_PATH/.claude/config.sh"
echo ""
echo "Next steps:"
echo "1. Restart Claude Code (or reload with /restart if available)"
echo "2. Test with: /capture https://youtube.com/watch?v=..."
echo "3. Try publishing: /publish my-note.md"
echo ""
echo "Available commands:"
echo "  /capture   - Universal content capture"
echo "  /publish   - Publish to GitHub Pages"
echo "  /idea      - Quick idea capture"
echo "  /youtube-note - YouTube video notes"
echo "  /study-guide  - Generate study guides"
echo "  /semantic-search - Search your vault"
echo "  /bulk-auto-tag - Bulk tag existing notes"
echo ""

exit 0
